[platformio]
src_dir = firmware/cabinet_esp
data_dir = firmware/cabinet_esp/data

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

board_build.filesystem = littlefs

monitor_speed = 115200
upload_speed = 115200

lib_deps =
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    bblanchon/ArduinoJson
    knolleary/PubSubClient

build_flags =
    -DKMS_SECRETS_SET=1
    -Dmbedtls_md5_starts_ret=mbedtls_md5_starts
    -Dmbedtls_md5_update_ret=mbedtls_md5_update
    -Dmbedtls_md5_finish_ret=mbedtls_md5_finish
