"""add script_executions table

Revision ID: add_script_executions
Revises: b72767340ad7
Create Date: 2026-08-12 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_script_executions'
down_revision = 'b72767340ad7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('script_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'killed', 'failed', name='script_status'), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_executions_user_id'), 'script_executions', ['user_id'], unique=False)
    op.create_index(op.f('ix_script_executions_started_at'), 'script_executions', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_executions_started_at'), table_name='script_executions')
    op.drop_index(op.f('ix_script_executions_user_id'), table_name='script_executions')
    op.drop_table('script_executions')
    # ### end Alembic commands ###